apiVersion: v1
kind: Service
metadata:
  name: digit-prediction-app-service
spec:
  selector:
    app: digit-prediction-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Use "LoadBalancer" for cloud environments with external load balancers
